version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: koi_delivery_ordering_system
      MYSQL_USER: ulquiorra
      MYSQL_PASSWORD: 12345678
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql
  backend:
    build:
      context: ./koi-delivery-ordering-system
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/koi_delivery_ordering_system?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=ulquiorra
      - SPRING_DATASOURCE_PASSWORD=12345678
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./koi-delivery-ordering-system-client
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "5173:5173"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
